[feature/project-domain-api] 프로젝트 도메인 기본 CRUD 구현
HiFivee/Mine_Backend pull request #5
Opened 2022-05-06 09:49 UTC by sktmdgus1212

## 개요
### PR 종류
 - [x] 기능 구현을 위한 소스코드 수정 (PR제목 양식: "[feature/브랜치명] 제목", 브랜치작명법: "feature/명칭" 사용)
 - [ ] 버그 수정을 위한 소스코드 수정 (PR제목 양식: "[hotfix/브랜치명] 제목", 브랜치작명법: "hotfix/명칭" 사용)

## 작업내용
- 프로젝트 도메인 기본 CRUD 구현

## 변경사항
- Project Domain
   - REST API 설계 가이드라인을 바탕으로 Project CRUD API 엔드포인트를 구현
     - 프로젝트 생성(POST)
     - 프로젝트 조회(GET)
     - 프로젝트 전체 조회(GET)
     - 본인 프로젝트 조회(GET)
     - 프로젝트 전체 조회(GET)
     - 프로젝트 수정(PUT)
     - 프로젝트 삭제(DELETE)
 
## 비고
- Postman에 관련 테스트를 추가

2022-05-06 14:04 UTC, Komputer-P requested changes
- 일단 제가 생각하는 변경 사항은 아래와 같아요
  - Controller의 Get API 통일
  - Project Entity에서의 연관관계 설명 및 자바 컨벤션 네이밍 따르기
- API들은 모두 Postman에서 정상 작동하는 것을 확인했습니다!
- 위의 리펙토링 이후 GET API가 하나로 통일되면 다시 테스트 해봐야 할 것 같네요!

2022-05-08 16:11 UTC, hyeonjeongs approved these changes
수고하셨습니다 :)

2022-05-08 16:11 UTC, hyeonjeongs commented on src/main/java/org/hifivee/minebackend/domain/project/service/ProjectService.java
> +import javax.transaction.Transactional;
Transactional 선언하실때 springframework에서 지원하는 것으로 import 하셔야해요

2022-05-14 05:41 UTC, Komputer-P requested changes

2022-05-14 05:41 UTC, Komputer-P commented on src/main/java/org/hifivee/minebackend/global/security/WebSecurityConfig.java
> +                .antMatchers(HttpMethod.POST, "/api/project").permitAll()
계정 생성 등의 계정 영역 빼고 다른 도메인들은 JWT로 인증해서 여기는 더이상 추가하면 안돼요!

2022-05-14 05:41 UTC, Komputer-P commented on src/main/java/org/hifivee/minebackend/domain/project/repository/Project.java
> +    @ManyToOne(targetEntity = Account.class, fetch = FetchType.EAGER    )
여기 FetchType을 LAZY가 아니라 EAGER로 한 이유가 있을까요?

2022-05-15 05:55 UTC, sktmdgus1212 commented on src/main/java/org/hifivee/minebackend/domain/project/repository/Project.java
> +    @ManyToOne(targetEntity = Account.class, fetch = FetchType.EAGER    )
아 공부하면서 이것저것해보다가 바꿨는데 수정을 안했네요ㅎㅎ..

2022-05-15 14:25 UTC, Komputer-P approved these changes

2022-05-16 05:39 UTC, merged